Sharedptr
SoPra-Team-17/LibCommon pull request #137
Opened 2020-04-30 10:02 UTC by ottojo

2020-04-30 18:28 UTC, csacro requested changes

2020-04-30 18:28 UTC, csacro commented on src/datatypes/execution/ActionExecutor.cpp
> +                break;
Das könne man mit in den default reinnehmen

2020-04-30 18:28 UTC, csacro commented on src/datatypes/execution/ActionExecutor.cpp
> +                break;
Hiefür werden noch Methoden und Struktur mit TODO benötigt

2020-04-30 18:28 UTC, csacro commented on src/datatypes/gameplay/CatAction.hpp
> +            CatAction();
target sollte ein Parameter sein

2020-04-30 18:28 UTC, csacro commented on src/datatypes/gameplay/JanitorAction.hpp
> +            JanitorAction();
target sollte ein Parametere sein

2020-04-30 18:28 UTC, csacro commented on src/datatypes/gameplay/RetireAction.cpp
> +    }
CharacterOperation müsste hier verwendet werden

2020-04-30 18:28 UTC, csacro commented on src/datatypes/gameplay/SpyAction.hpp
> +    class SpyAction : public BaseOperation {
Sollte von CharacterOperation erben und dementsprechend Konstruktor mit characterId und auch to und from json anpassen und isEqual

2020-04-30 18:28 UTC, csacro commented on src/datatypes/gameplay/RetireAction.hpp
> +            RetireAction();
characterId als Parameter

2020-04-30 18:28 UTC, csacro commented on src/datatypes/validation/ActionValidator.cpp
> +                break;
Methoden müssen definiert werden und Struktur mit todo

2020-04-30 18:28 UTC, csacro commented on src/datatypes/validation/ActionValidator.cpp
> +                break;
mit in default case

2020-04-30 18:28 UTC, csacro commented on src/network/messages/GameStatus.hpp
> +#include <datatypes/gameplay/CharacterOperation.hpp>
hier sollte BaseOperation included werden

2020-04-30 18:28 UTC, csacro commented on src/util/OperationSerialization.hpp
> +                    throw std::invalid_argument("Operation type not valid");
mit in default und sollte nach convention als BaseOperation behandelt werden und nichts schmeißen, wenn ich das richtig in Erinnerung habe

2020-04-30 18:28 UTC, csacro commented on src/util/OperationSerialization.hpp
> +                    throw std::invalid_argument("Operation type not valid");
mit in default und sollte nach convention als BaseOperation behandelt werden und nichts schmeißen, wenn ich das richtig in Erinnerung habe

2020-04-30 18:28 UTC, csacro commented on src/datatypes/gameplay/Exfiltration.cpp
> +        return from == rhs.from;
isCharacterEqual fehlt

2020-05-01 13:41 UTC, ottojo commented on src/util/OperationSerialization.hpp
> +                    throw std::invalid_argument("Operation type not valid");
Dieser Fall tritt ein, wenn `type` kein element aus dem enum annimmt, ich finde dazu nix im standard

2020-05-01 13:42 UTC, ottojo commented on src/util/OperationSerialization.hpp
> +                    throw std::invalid_argument("Operation type not valid");
nevermind, das ist ja to_json. Ich würde da trotzdem eine exception schmeißen, wenn wir versuchen eine Operation ohne typ zu verschicken, machen wir was falsch...

2020-05-01 13:45 UTC, ottojo commented on src/util/OperationSerialization.hpp
> +                    throw std::invalid_argument("Operation type not valid");
hier im from_json finde ich das auch nicht sinnvoll da ohne warnung zu ignorieren, dass wir gerade eine unbekannte operation bekommen haben

2020-05-01 13:49 UTC, csacro commented on src/util/OperationSerialization.hpp
> +                    throw std::invalid_argument("Operation type not valid");
Ok, dachte das default bei uns ja eh immer INVALID wäre, aber passt.

2020-05-01 13:50 UTC, csacro commented on src/util/OperationSerialization.hpp
> +                    throw std::invalid_argument("Operation type not valid");
siehe oben (default: INVALID bei uns), aber passt

2020-05-01 13:57 UTC, csacro approved these changes

2020-05-01 15:09 UTC, authaldo approved these changes

2020-05-01 15:12 UTC, merged