Matchconfig for validation and execution
SoPra-Team-17/LibCommon pull request #139
Opened 2020-05-01 17:30 UTC by authaldo

fixes #133

2020-05-01 19:12 UTC, authaldo commented
Ich habe in diesem PR eigentlich nicht vor die Code Coverage zu fixen.

2020-05-01 20:13 UTC, ottojo requested changes

2020-05-01 20:13 UTC, ottojo commented on src/datatypes/execution/ActionExecutor.hpp
> +#include "datatypes/matchconfig/MatchConfig.hpp"
bitte nicht

2020-05-01 20:13 UTC, ottojo commented on src/datatypes/execution/ActionExecutor_Movement.cpp
> +            charTarget->setCoordinates(op.getFrom());
```suggestion
        if (charTarget != s.getCharacters().end()) {
            // characters need to swap places
            charTarget->setCoordinates(op.getFrom());
```

2020-05-01 20:13 UTC, ottojo commented on src/datatypes/execution/ActionExecutor_Movement.cpp
> +        if (gadget.has_value()) {                                       // pick up gadget
```suggestion
        if (gadget.has_value()) {
        // pick up gadget
```

2020-05-01 20:13 UTC, ottojo commented on src/datatypes/execution/gadget/GadgetExecutor.hpp
> +#include "datatypes/matchconfig/MatchConfig.hpp"
why?

2020-05-01 20:13 UTC, ottojo commented on src/datatypes/validation/ActionValidator.hpp
> +#include "datatypes/matchconfig/MatchConfig.hpp"
why?

2020-05-01 20:13 UTC, ottojo commented on src/datatypes/validation/gadget/GadgetValidator.hpp
> +#include "datatypes/matchconfig/MatchConfig.hpp"
why?

2020-05-01 20:13 UTC, ottojo commented on src/network/messages/GameOperation.cpp
> +#include "datatypes/validation/ActionValidator.hpp"
why?

2020-05-01 20:13 UTC, ottojo commented on src/network/messages/GameOperation.hpp
> +#include "datatypes/matchconfig/MatchConfig.hpp"
why?

2020-05-01 20:13 UTC, ottojo commented on src/network/messages/GameOperation.hpp
> +             * @param config            Configuration of the current match.
```suggestion
             * Validate message according role and operation type and if operation is allowed in current state.
             * @param playerRole        Role of the player who sent the message.
             * @param state             current state of the game.
             * @param activeCharacter   Character that move was requested from.
             * @param config            Configuration of the current match.
```

2020-05-02 11:53 UTC, csacro requested changes
Was mir gerade zu den Validate-Sachen auffällt:
* Braucht der Server eine validate für Exfiltration und Janitor- und CatAction ? Weil eigentlich macht der das halt einfach richtig (wäre ja schlecht, wenn der Server seine eigenen Aktionen validieren muss).  
Der Client darf das ja nicht ausführen, aber das wird schon bei der Nachricht selber abgefangen.  
--> Können die validate und zugehörige Issues weg ?

edit: Statt der validate brauchen wir eher eine generate Funktion.

2020-05-02 11:53 UTC, csacro commented on src/datatypes/execution/ActionExecutor.cpp
>                  return ActionExecutor::executeSpy(s, *std::dynamic_pointer_cast<const gameplay::SpyAction>(op));
braucht auch Matchconfig (Spionage-Erfolgs-Wahrscheinlichkeit)

2020-05-02 11:53 UTC, csacro commented on src/datatypes/execution/ActionExecutor.cpp
> +                return ActionExecutor::executeProperty(s,
braucht auch MatchConfig (Observatations-Erfolg-Wahrscheinlichkeit)

2020-05-02 12:08 UTC, ottojo commented on src/datatypes/execution/ActionExecutor_Movement.cpp
> +            character->addGadget(gadget.value());
```suggestion
        if (gadget.has_value()) {
            // pick up gadget
            character->addGadget(gadget.value());
```

2020-05-02 12:43 UTC, csacro approved these changes

2020-05-02 19:00 UTC, ottojo approved these changes

2020-05-02 19:02 UTC, merged