Utility Methods for round initialization
SoPra-Team-17/LibCommon pull request #170
Opened 2020-05-04 11:47 UTC by authaldo

2020-05-04 19:43 UTC, authaldo commented
Blocked by PR #181

2020-05-05 13:53 UTC, ottojo requested changes

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
das sollte man nur machen wenn der state sich auch geändert hat

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
siehe oben

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
siehe oben

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
siehe oben

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
siehe oben

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
siehe oben

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
siehe oben

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::updated = true;
siehe oben

2020-05-05 13:53 UTC, ottojo commented on src/datatypes/scenario/Field.hpp
> +            unsigned int fogCounter = 0;
Ich glaube hier wäre dokumentation gut, dass das ein member ist, der nicht übers netzwerk geschickt wird

2020-05-05 13:53 UTC, ottojo commented on src/util/RoundUtils.hpp
> +            static void checkGadgetFallouts(spy::gameplay::State &s, const MatchConfig &config);
ich glaube fallout ist nicht das richtige wort hier

2020-05-05 13:53 UTC, ottojo commented on src/util/RoundUtils.cpp
> +        for (unsigned int y = 0; y < s.getMap().getNumberOfRows(); y++) {
Kann man der Map iteratoren spendieren? dann würde man sich hier ein bisschen verschachtelung sparen

2020-05-05 13:53 UTC, ottojo commented on src/util/RoundUtils.cpp
> +                auto wiretap = std::static_pointer_cast<spy::gadget::WiretapWithEarplugs>(gadget.value());
dynamic_pointer_cast für runtime-checks

2020-05-05 18:09 UTC, authaldo commented on src/util/RoundUtils.cpp
> +                auto wiretap = std::static_pointer_cast<spy::gadget::WiretapWithEarplugs>(gadget.value());
Aufgrund der vorherigen Methoden sollte eigentlich sichergestellt sein, dass das Objekt hinter dem Ptr wirklich ein Wiretap with earplugs Objekt ist. Aber ich habs dennoch mal zu einem dynamic cast geändert.

2020-05-05 19:22 UTC, ottojo requested changes

2020-05-05 19:22 UTC, ottojo commented on src/datatypes/scenario/Field.hpp
> +            unsigned int fogCounter = 0;                        // only used for fog tin, will not be serialized
doxygen-comment

2020-05-05 20:22 UTC, ottojo commented on src/datatypes/scenario/Field.hpp
> +            unsigned int fogCounter = 0;                        ///< Only used for fog tin, will not be serialized.
```suggestion
            unsigned int fogCounter = 0; ///< Only used for fog tin, will not be serialized.
```

2020-05-05 21:34 UTC, ottojo approved these changes

2020-05-06 08:11 UTC, Marco5de approved these changes

2020-05-06 08:11 UTC, Marco5de commented on src/datatypes/scenario/Field.cpp
> +            if (fieldState != FieldStateEnum::ROULETTE_TABLE) {
Wofür braucht man das?

2020-05-06 10:03 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +            if (fieldState != FieldStateEnum::ROULETTE_TABLE) {
Ich nehme an, dass hier verhindert werden soll, dass Felder != Roulette optionen haben, die nur für die Roulette-Tische relevant sind

2020-05-06 10:05 UTC, authaldo commented on src/datatypes/scenario/Field.cpp
> +            if (fieldState != FieldStateEnum::ROULETTE_TABLE) {
Im Spiel selbst sollte beim Feldtyp eigentlich nur der Wechsel von WALL zu FREE durch einen Raketenwerfer vorkommen.
Ich hab hier trotzdem mal noch das Resetten von optionalen Eigenschaften für den Fall eines Wechsels zu einem anderen Typ eingebaut. Ob das wirklich zum Einsatz kommt weiß ich nicht, aber es ist auf jeden Fall gewährleistet, dass keine ungültigen Kombinationen der Member entstehen.

2020-05-06 12:53 UTC, csacro commented on src/util/RoundUtils.cpp
> +                    wiretap->setWorking(false);
Kann die Wanze nicht erst ausfallen nachdem die platziert wurde ?

2020-05-06 14:14 UTC, merged