execute cocktail
SoPra-Team-17/LibCommon pull request #202
Opened 2020-05-05 11:41 UTC by Marco5de

2020-05-05 14:55 UTC, csacro requested changes

2020-05-05 14:55 UTC, csacro commented on src/gameLogic/execution/gadget/Cocktail.cpp
> +        bool success = util::GameLogicUtils::probabilityTestWithCharacter(*targetChar, config.getCocktailDodgeChance());
nachdem CocktailDodgeChance die Ausweichwahrscheinlichkeit ist und somit bei Erfolgreichem Test die Action fehlschlägt muss entweder die Variable und ihre Verwendung gefixt werden oder der Test mit 1-CocktailDodgeChange ausgefführt werden

2020-05-06 10:06 UTC, ottojo approved these changes

2020-05-06 10:08 UTC, authaldo approved these changes
Nachdem der Charakter jetzt eine addProperty hat, könnte man sich überlegen ihm auch noch eine removeProperty zu geben.

2020-05-06 10:09 UTC, ottojo commented
> Nachdem der Charakter jetzt eine addProperty hat, könnte man sich überlegen ihm auch noch eine removeProperty zu geben.

bitte nicht so viele unrelated changes... Machen wir das sobald man das braucht

2020-05-06 10:17 UTC, csacro approved these changes

2020-05-06 12:01 UTC, csacro requested changes

2020-05-06 12:01 UTC, csacro commented on src/gameLogic/execution/gadget/Cocktail.cpp
> +                    sourceChar->getGadget(gadget::GadgetEnum::COCKTAIL));
muss hier noch `.value()` hin ?

2020-05-06 13:15 UTC, csacro requested changes

2020-05-06 13:15 UTC, csacro commented on src/gameLogic/execution/gadget/Cocktail.cpp
> +            targetChar->addProperty(character::PropertyEnum::CLAMMY_CLOTHES);
Nach der Implementierung von HairDryer sollte Clammy Clothes nur hinzugefügt werden, wenn der Charakter nicht die Eigenschaft konstan klamme Klamotten besitzt

2020-05-07 08:13 UTC, Marco5de commented on src/gameLogic/execution/gadget/Cocktail.cpp
> +            targetChar->addProperty(character::PropertyEnum::CLAMMY_CLOTHES);
Wieso?

2020-05-07 13:41 UTC, csacro commented on src/gameLogic/execution/gadget/Cocktail.cpp
> +            targetChar->addProperty(character::PropertyEnum::CLAMMY_CLOTHES);
Wann wird dann klamme Klamotten wieder entfernt?
Vorallem bringt es nichts klamme Klamotten hinzuzufügen, wenn man eh konstant klamme Klamotten hat.

2020-05-07 14:14 UTC, Marco5de commented on src/gameLogic/execution/gadget/Cocktail.cpp
> +            targetChar->addProperty(character::PropertyEnum::CLAMMY_CLOTHES);
Ja genau warum dann ein sonderfall einführen wenn es keinen Unterschied macht?

2020-05-07 14:35 UTC, csacro approved these changes

2020-05-07 14:35 UTC, merged