initial match config class
SoPra-Team-17/LibCommon pull request #21
Opened 2020-04-05 09:58 UTC by authaldo

Addresses #15 for the match config class.

2020-04-05 10:13 UTC, authaldo commented
Für die json Struktur wurde im Standard ein json Schema eingebettet, welches man zur Validierung nutzen könnte. nlohmann::json unterstützt dies meines Wissens nach aber nicht.
Bis zu einem gewissen Grad validieren wir beim Parsen ja, für alle nicht vorhandenen Elemente fliegt eine Exception.
Allerdings reagieren wir vermutlich nicht auf zusätzliche Elemente, wobei hier die Frage ist ob diese Reaktion überhaupt relevant wäre.

Was die Exceptions angeht bin ich am Überlegen den Inhalt der from_json in eine try catch zu packen und eine eigene Exception zu werfen, was haltet ihr davon?

2020-04-05 13:27 UTC, ottojo commented
Ich würde zusätzliche Elemente ignorieren.  
json-schema wäre cool, muss man mal ausprobieren wie viel Aufwand das wäre.  
Dann könnte man halt beim Laden der Config eine gute Fehlermeldung geben.

Warum willst du eigene exceptions werfen? nlohmann::json wirft bereits exceptions bei fehlenden Elementen, finde ich ausreichend.

2020-04-05 13:36 UTC, ottojo commented on test/CMakeLists.txt
> +target_link_libraries(allTests gtest gmock gtest_main SopraCommon nlohmann_json::nlohmann_json stdc++fs)
warum stdc++fs?

2020-04-05 13:38 UTC, authaldo commented on test/CMakeLists.txt
> +target_link_libraries(allTests gtest gmock gtest_main SopraCommon nlohmann_json::nlohmann_json stdc++fs)
Das ist noch ein Überbleibsel, ich wollte die json Datei erst so hinterlegen, aber die String Variante war deutlich einfacher.

2020-04-05 13:40 UTC, ottojo approved these changes

2020-04-05 19:27 UTC, authaldo commented
Der Code Smell ist leider bedingt durch den Standard

2020-04-05 19:29 UTC, ottojo commented on test/CMakeLists.txt
> +add_executable(allTests gadgetTest.cpp jsonEncodingTest.cpp jsonDecodingTest.cpp characterTest.cpp)
Hier ist beim mergen die `matchConfigTest.cpp` rausgeflogen glaube ich

2020-04-05 19:38 UTC, ottojo approved these changes

2020-04-06 13:02 UTC, csacro requested changes

2020-04-06 13:02 UTC, csacro commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            friend void from_json(const nlohmann::json &j, MatchConfig &c);
to_json fehlt noch (general note, darf man nicht vergessen)

2020-04-06 13:02 UTC, csacro commented on src/datatypes/matchconfig/MatchConfig.hpp
> +             */
brauchen wir die Kommentare wirklich, siehe [hier](https://github.com/SoPra-Team-17/LibCommon/pull/19#discussion_r403741917)

2020-04-06 13:02 UTC, csacro commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            MatchConfig();
Sollte man im Konstruktor nicht die ganzen Werte setzen können ?

2020-04-06 13:02 UTC, csacro commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            unsigned int strikeMaximum;
Wieso gibt es keine Setter ?
Im Client sollte man die Werte meines Wissens nach setzen können.

2020-04-06 13:13 UTC, authaldo commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            friend void from_json(const nlohmann::json &j, MatchConfig &c);
Ich hab das so verstanden, dass die Match-Config vom Editor erstellt wird, den wir ja von einem anderen Team nutzen müssen. Daher ist die Klasse lediglich auf das parsen der json Datei und anschließendes weitergeben der Werte ausgelegt

2020-04-06 13:20 UTC, csacro commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            friend void from_json(const nlohmann::json &j, MatchConfig &c);
Stimmt, das macht ja der Editor.
Dann passt das, sry

2020-04-06 13:20 UTC, csacro commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            unsigned int strikeMaximum;
done by Editor

2020-04-06 13:21 UTC, csacro commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            MatchConfig();
done by Editor

2020-04-06 13:39 UTC, csacro approved these changes

2020-04-06 14:21 UTC, ottojo approved these changes

2020-04-06 14:27 UTC, merged

2020-04-07 22:24 UTC, ottojo commented
Die MatchConfig to_json brauchen wir im Server, weil man die serialisieren muss um sie zum client zu schicken, in der ConfigDeliveryMessage