Execute with honey trap
SoPra-Team-17/LibCommon pull request #211
Opened 2020-05-06 16:54 UTC by csacro

fixes #201 
Es ist noch zu klären, welche Aktionen auf Honey Trap testen müssen.

2020-05-06 18:10 UTC, authaldo approved these changes
Ich find a etwas kurz als Benennung, aber rückblickend muss man leider sagen, dass wir es beim State mit s auch nicht anders gemacht haben.

2020-05-06 18:11 UTC, csacro commented
Ursprünglich war a der Übergabeprameter. Dann war es am einfachsten die neue Variable a zu nennen und den Übergabeprameter umzubennen.

2020-05-07 09:43 UTC, ottojo requested changes

2020-05-07 09:43 UTC, ottojo commented on src/util/GameLogicUtils.hpp
> +            static const gameplay::GadgetAction
warum ist das const?

2020-05-07 09:43 UTC, ottojo commented on src/util/GameLogicUtils.cpp
> +        }
```suggestion
        for (const auto &character: s.getCharacters()) {
            if (character.getCharacterId() == sourceChar->getCharacterId() ||
                character.getCharacterId() == targetChar->getCharacterId()) {
                // alternative action target is source or target
                continue;
            }

            auto otherTarget = character.getCoordinates().value();
            if (s.getMap().isInside(otherTarget)) {
                a.setTarget(otherTarget);
                if (gameplay::ActionValidator::validate(s, std::make_shared<gameplay::GadgetAction>(a), config)) {
                    alternativeTargets.push_back(otherTarget);
                }
            }
        }
```

2020-05-07 12:04 UTC, csacro commented on src/util/GameLogicUtils.hpp
> +            static const gameplay::GadgetAction
Wieso nicht ? Also das darf ja const sein.

2020-05-08 08:44 UTC, Marco5de commented on src/gameLogic/execution/gadget/Cocktail.cpp
> +        bool doHoneyTrap = util::GameLogicUtils::isPersonOnField(s, a.getTarget());
Ist das nicht immer true?

2020-05-08 08:52 UTC, Marco5de commented on src/util/GameLogicUtils.cpp
> +            auto otherTarget = character.getCoordinates().value();
Du kannst hier glaub ich nicht davon ausgehen, dass das Optional einen Wert hat

2020-05-08 12:28 UTC, ottojo commented on src/util/GameLogicUtils.hpp
> +            static const gameplay::GadgetAction
das bringt halt ziemlich wenig. hier wird ja eine kopie zurückgegeben, die kann man ohne probleme auch einer non-const GadgetAction assignen.

2020-05-08 12:54 UTC, Marco5de approved these changes

2020-05-08 13:18 UTC, csacro commented on src/util/GameLogicUtils.hpp
> +            static const gameplay::GadgetAction
ok

2020-05-08 13:25 UTC, ottojo approved these changes

2020-05-08 13:39 UTC, merged