generate hair dryer
SoPra-Team-17/LibCommon pull request #235
Opened 2020-05-08 14:19 UTC by Marco5de

2020-05-08 16:11 UTC, csacro approved these changes
generateBowlerBlade passt hier nicht (Angriff auf sich selbst noch möglich), aber ist nicht teil des pr.
Im tatsächlichen Bowler Bade pr passt alles

2020-05-12 19:32 UTC, ottojo requested changes

2020-05-12 19:32 UTC, ottojo commented on src/gameLogic/generation/actions/gadget/BowlerBlade.cpp
> +    ActionGenerator::generateBowlerBlade(const State &s, const util::UUID &activeCharacter,
warum ist das hier drin?

2020-05-12 19:32 UTC, ottojo commented on src/gameLogic/generation/actions/gadget/HairDryer.cpp
> +                valid_ops.erase(std::remove(valid_ops.begin(), valid_ops.end(), ops), valid_ops.end());
Diese for-schleife sollte man ersetzen durch `valid_ops.erase(std::remove_if(...`

2020-05-15 14:15 UTC, Marco5de commented on src/gameLogic/generation/actions/gadget/BowlerBlade.cpp
> +    ActionGenerator::generateBowlerBlade(const State &s, const util::UUID &activeCharacter,
durch develop merge hinfällig

2020-05-15 18:43 UTC, ottojo approved these changes

2020-05-15 18:43 UTC, ottojo commented on src/gameLogic/generation/actions/gadget/HairDryer.cpp
> +                                           return ActionValidator::validate(s, action, config);
hier werden alle validen aktionen entfernt, ich glaube das sollte genau das gegenteil sein

2020-05-15 18:44 UTC, ottojo requested changes
siehe kommentar

2020-05-15 18:44 UTC, ottojo commented on src/gameLogic/generation/actions/gadget/HairDryer.cpp
> +                                           return ActionValidator::validate(s, action, config);
(ups das sollte kein approve sein)

2020-05-25 18:16 UTC, ottojo approved these changes

2020-05-26 07:09 UTC, merged