generate Spy action
SoPra-Team-17/LibCommon pull request #243
Opened 2020-05-08 14:59 UTC by csacro

implementes #218

2020-05-09 13:45 UTC, Marco5de approved these changes

2020-05-12 19:29 UTC, ottojo requested changes

2020-05-12 19:29 UTC, ottojo commented on src/gameLogic/generation/actions/SpyActions.cpp
> +            auto action = std::make_shared<Movement>(Movement(false, p, activeCharacter, character->getCoordinates().value()));
wird hier mit absicht ein Movement und nicht SpyAction generiert?

2020-05-15 18:39 UTC, ottojo approved these changes

2020-05-15 21:58 UTC, merged