generate laser compact
SoPra-Team-17/LibCommon pull request #244
Opened 2020-05-08 15:11 UTC by Marco5de

2020-05-08 16:15 UTC, csacro requested changes

2020-05-08 16:15 UTC, csacro commented on src/gameLogic/generation/actions/gadget/LaserCompact.cpp
> +            return util::GameLogicUtils::hasCocktail(s, p);
sollte auch `true ` returnen, wenn Charakter Cocktail hält

2020-05-08 16:19 UTC, csacro approved these changes

2020-05-09 09:03 UTC, csacro approved these changes

2020-05-12 19:27 UTC, ottojo approved these changes

2020-05-13 12:31 UTC, merged