generate cocktail
SoPra-Team-17/LibCommon pull request #257
Opened 2020-05-08 16:48 UTC by Marco5de

2020-05-08 17:34 UTC, csacro requested changes

2020-05-08 17:34 UTC, csacro commented on src/gameLogic/generation/actions/gadget/Cocktail.cpp
> +                                                                                        s, p);
Cocktail kann auch von benachbartem Bar-Tisch aufgenommen werden

2020-05-15 16:39 UTC, csacro approved these changes

2020-05-15 18:38 UTC, ottojo approved these changes

2020-05-16 09:53 UTC, merged