[FIX] added initialization of optional elements of the roulette table
SoPra-Team-17/LibCommon pull request #279
Opened 2020-05-20 20:31 UTC by authaldo

Bei der Konstruierung des Feldes wurden in der Field Klasse die optionals nicht initialisiert. Dadurch kam es im Server bei NPC moves dazu, dass in der validateGamble ein bad optional access flog, weil der destroyed Wert nicht gesetzt war.

2020-05-20 20:34 UTC, ottojo requested changes

2020-05-20 20:34 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +            if (fieldState == FieldStateEnum::ROULETTE_TABLE) {
in der funktionsdokumentation sollte stehen, dass dadurch die felder gecleared werden (kein erwartetes verhalten von einem setter)

2020-05-21 17:11 UTC, ottojo approved these changes

2020-05-22 07:38 UTC, csacro reviewed
Es gibt ja noch mehr optionals in der Field Klasse: Sollte man die auch mit behandlen?
Evtl. wäre eine private Methode `initialize(FieldStateEnum)` oder so praktisch, damit man sich dann den duplicate Code im Konstruktor und in der setField Methode sparen kann.

2020-05-27 14:22 UTC, csacro approved these changes

2020-05-27 14:47 UTC, merged