Implementation of spy action
SoPra-Team-17/LibCommon pull request #292
Opened 2020-05-30 20:56 UTC by authaldo

2020-05-30 21:05 UTC, ottojo requested changes

2020-05-30 21:05 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +        auto targetChar = util::GameLogicUtils::findPersonOnNeighbourField(s, op.getTarget(),
eigenschaft für spy mit distance>1

2020-05-30 21:05 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +                                && f.getSafeIndex().has_value()
das kann angenommen werden, wenn das keine value hat ist der state ungültig.

2020-05-30 21:06 UTC, ottojo commented
bitte den grad der verschachtelung reduzieren durch hilfsfunktionen

2020-05-30 21:09 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +                retOp->setSuccessful(false);
kann man das hier mit weniger verschachtelung weiter oben durch
```
if ( faction not NEUTRAL) {
    success = false;
    return;
}
```

lösen?

2020-05-31 10:35 UTC, csacro requested changes
Den `maxSafeIndex` könnte man als zusätzlichen member von `State` machen und im Konstruktor mit initialisieren, denn der Wert ändert sich während des gesamten Spiels nicht (zumindest für mein Verständnis). Um die Komplexität rauszunehmen, könntest du die bereits existierende GameLogicUtils Methode `getAllFieldsWith(...)` nutzen und dann die Länge des return Vektors als `maxSafeIndex` setzen.

Genauso könnte `collarOnMap` ein member von `State` sein, der initial `false` ist und in der execute im case `// first character gets diamond collar` auf true gesetzt wird.

2020-05-31 10:35 UTC, csacro commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +            s.addSafeCombination(secret);
Woher weiß der Server, welcher Spieler welche Safe Kombinationen hat?
Er darf ja den Clients jeweils nur ihre eigenen schicken.

2020-05-31 11:14 UTC, authaldo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +            s.addSafeCombination(secret);
Der Server hat intern eine Map, die nach der Execution einer Spy-Action aktualisiert werden muss. 
Ist zwar nicht wirklich schön, aber der State bildet halt nur die Sichtweise einer Fraktion ab

2020-05-31 11:46 UTC, ottojo requested changes

2020-05-31 11:46 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +    handleSpyOnPerson(State &s, const SpyAction &op, const MatchConfig &config,
forward declaration bitte in header

2020-05-31 11:46 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +    handleSpyOnSafe(State &s, const SpyAction &op, const MatchConfig &config,
s.o.

2020-05-31 11:46 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +    handleSpyOnPerson(State &s, const SpyAction &op, const MatchConfig &config,
(oder wenn du die hier lassen willst, halt nicht forward declaren sondern direkt hier hinschreiben)

2020-05-31 11:46 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +                    && f.getSafeIndex().has_value()
sollen safes ohne index gültig sein? würde vielleicht sinn machen hier im zweifelsfall zu throwen

2020-05-31 11:46 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +                       && f.getGadget().value()->getType() == gadget::GadgetEnum::DIAMOND_COLLAR) {
```suggestion
            } else if (f.getGadget().value_or(gadget::GadgetEnum::INVALID) == gadget::GadgetEnum::DIAMOND_COLLAR) {
```

2020-05-31 13:31 UTC, authaldo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +                       && f.getGadget().value()->getType() == gadget::GadgetEnum::DIAMOND_COLLAR) {
Du vergleichst hier Äpfel mit Birnen, getGadget liefert einen shared_ptr auf ein Gadget, nicht das Enum

2020-05-31 13:44 UTC, ottojo commented
Bin kein fan von den member variablen - das passiert schnell dass die info divergiert vom eigentlichen zustand. Momentan wird das z.b. nicht updated wenn der State deserialisiert wird...

2020-05-31 15:01 UTC, ottojo commented on src/gameLogic/execution/ActionExecutor_Spy.cpp
> +                       && f.getGadget().value()->getType() == gadget::GadgetEnum::DIAMOND_COLLAR) {
ach so

2020-05-31 15:03 UTC, ottojo approved these changes

2020-05-31 18:50 UTC, ottojo approved these changes

2020-06-01 10:07 UTC, csacro approved these changes

2020-06-01 14:01 UTC, merged