operator < for Gadget
SoPra-Team-17/LibCommon pull request #308
Opened 2020-06-09 17:52 UTC by csacro

to make work in map and set

2020-06-09 20:24 UTC, ottojo requested changes
Finde ich nicht sinnvoll. Besonders bei den shared pointern ist dann nicht klar was verglichen wird. Und bei den punkten könnte man aus `!(a<b)` und `!(b<a)` folgern dass `b==a`, was aber z.b. für `(1,1)` und `(2,2)` nicht gilt.

2020-06-09 20:25 UTC, ottojo commented
Dieses Problem sollte anders gelöst werden. Z.b. mit `unordered_` containern, oder einer ordnungsfunktion die nur für den jeweiligen container verwendet werden soll.

2020-06-10 09:50 UTC, ottojo approved these changes

2020-06-10 10:18 UTC, authaldo approved these changes

2020-06-10 11:28 UTC, merged