Network messages
SoPra-Team-17/LibCommon pull request #32
Opened 2020-04-08 22:48 UTC by ottojo

fixes #24

2020-04-09 01:20 UTC, ottojo commented
Ist zwar noch nicht fertig, wird aber großzügig viel, review kann also gerne schon angefangen werden...

Github kann das ja ganz gut dass man nur Sachen reviewt die man noch nicht angeschaut hat.

2020-04-10 17:25 UTC, Marco5de commented on src/network/messages/Hello.cpp
> +        MessageContainer::common_to_json(j, h);
> Wichtig: Diese Nachricht hält das clientId-Feld im MessageContainer frei – genauer gesagt wird
es vom Server ignoriert!

sollte also in Ordnung sein

2020-04-10 17:32 UTC, Marco5de commented on src/network/messages/ItemChoice.hpp
> +            util::UUID chosenCharacter;
Eines der beiden Attribute wird explizit `null` gesetzt.
Sinnvolle repräsentation dafür?

2020-04-10 17:35 UTC, Marco5de commented on src/network/messages/StatisticsMessage.hpp
> +            spy::statistics::Statistics statistics;
Feld ist optional und sollte auch als solches implementiert werden.

2020-04-10 18:31 UTC, ottojo commented on src/network/MessageContainer.cpp
> +    // TODO initialize creationdate
-> Low Prio -> issue

2020-04-10 18:31 UTC, ottojo commented on src/network/MessageContainer.hpp
> +            static void common_to_json(nlohmann::json &j, const T &message) {
das müsste doch auch mit `MessageContainer` statt `typename T` gehen, das ist vielleicht sinnvoller.

2020-04-10 18:31 UTC, ottojo commented on src/network/MessageContainer.hpp
> +            static void common_from_json(const nlohmann::json &j, T &message) {
siehe oben

2020-04-10 18:31 UTC, ottojo commented on src/util/OptionalSerialization.hpp
> +// TODO less criminal C++ (thou shalt not hack the std namespace)
Das müsste auf develop schon gefixt sein -> merge

2020-04-10 19:15 UTC, ottojo commented on src/network/messages/ItemChoice.hpp
> +            util::UUID chosenCharacter;
Kann man bestimmt fancy mit `std::variant` machen. Ich prüfe das mal

2020-04-10 20:04 UTC, ottojo commented on src/network/messages/ItemChoice.hpp
> +            util::UUID chosenCharacter;
done.

2020-04-11 19:08 UTC, csacro commented on src/datatypes/character/CharacterInformation.hpp
> +            friend void from_json(const nlohmann::json &j, CharacterInformation &c);
duplicat code
diese Methoden sollten gelöscht werden (die zwei analogen Methoden darüber wurden implementiert)

2020-04-11 19:09 UTC, authaldo requested changes

2020-04-11 19:09 UTC, authaldo commented on src/datatypes/character/CharacterInformation.hpp
> +            friend void from_json(const nlohmann::json &j, CharacterInformation &c);
Eventuell merge Überbleibsel? to_json und from_json gibts doch schon?

2020-04-11 20:00 UTC, authaldo requested changes
Ich bin generell Fan von Doxygen Headern und Kommentaren, aber die kann man auch noch im Verlauf ergänzen. Außerdem finde ich es komisch, dass die Kommentare teilweise auf deutsch sind (z.b.MessageTypeEnum.hpp), vielleicht könnte man da einheitlich bei Englisch bleiben.

2020-04-11 20:00 UTC, authaldo commented on src/network/messages/Replay.hpp
> +            int rounds;
Warum nicht unsigned?

```suggestion
            unsigned int rounds;
```

2020-04-11 20:00 UTC, authaldo commented on src/network/messages/Strike.hpp
> +            int strikeMax;
Hier könnte man auch über unsigned nachdenken, bisher steht im Standard noch nichts davon, dass es für strike max eine infinte Option (bspw. über negative Werte) geben muss.

2020-04-11 20:02 UTC, ottojo commented on src/network/messages/Replay.hpp
> +            int rounds;
Gute idee, mach ich

2020-04-11 20:05 UTC, ottojo commented on src/network/messages/Strike.hpp
> +            int strikeMax;
Würde ich so lassen aufgrund deiner Argumente.

2020-04-11 20:07 UTC, ottojo commented
Vorschlag zur Coverage: Ich bastel gerade was, das mit wenig Aufwand pro Typ eine Beispielnachricht encoded und wieder decoded. Das sollte wenigstens Konsistenz sichern. Falls es in diesem Hinblick später Probleme gibt, kann man ja immer noch Testdaten generieren + nutzen, oder schemas bauen und so.

Dominik hat vorgeschlagen das in neuem PR zu machen, finde ich OK.

2020-04-11 20:25 UTC, authaldo approved these changes

2020-04-12 09:30 UTC, csacro requested changes
`MetaInformation.hpp` und `MetaInformation.cpp` fehlen (`MetaInformationMessage` page 42 im aktuellen Standard).

2020-04-12 09:30 UTC, csacro commented on src/network/messages/HelloReply.hpp
> +            std::vector<character::CharacterInformation> characterSettings;
how to access fields -> getter

2020-04-12 09:30 UTC, csacro commented on src/network/MessageContainer.hpp
> +            std::optional<std::string> debugMessage;
how to access fields -> getter
für die `debugMessage` wäre noch ein setter gut

2020-04-12 09:30 UTC, csacro commented on src/network/ErrorTypeEnum.hpp
> +            INVALID,
Im Standard gibt es noch `GENERAL` im `ErrorTypeEnum`. Man könnte sich auch überlegen das als default statt `INVALID` zu nehmen

2020-04-12 09:30 UTC, csacro commented on src/network/messages/RequestEquipmentChoice.hpp
> +            explicit RequestEquipmentChoice(const util::UUID &playerId);
Sollte man nicht im Konstruktor auch `chosenCharacterIds` und `chosenGadgets` setzen können ?

2020-04-12 09:30 UTC, csacro commented on src/network/messages/RequestItemChoice.hpp
> +            explicit RequestItemChoice(const util::UUID &playerId);
Sollte man im Konstruktor nicht auch `offeredCharacterIds` und `offeredGadgets` setzen können ?

2020-04-12 09:30 UTC, csacro commented on src/network/messages/EquipmentChoice.hpp
> +            explicit EquipmentChoice(util::UUID playerId);
Sollte man im Konstruktor nicht `equipment` setzen können ?

2020-04-12 09:30 UTC, csacro commented on src/network/messages/GameOperation.hpp
> +            gameplay::Operation operation;
how to acces `operation` -> getter

2020-04-12 09:30 UTC, csacro commented on src/network/messages/GamePause.hpp
> +            bool gamePause = false;
fehlendes Feld: `boolean serverEnforced`

2020-04-12 09:30 UTC, csacro commented on src/datatypes/statistics/VictoryEnum.hpp
> +            VICTORY_BY_KICK
Sollen wir hier auch noch einen extra default `INVALID` oder so machen ?

2020-04-12 09:36 UTC, csacro commented
> 
> 
> Vorschlag zur Coverage: Ich bastel gerade was, das mit wenig Aufwand pro Typ eine Beispielnachricht encoded und wieder decoded. Das sollte wenigstens Konsistenz sichern. Falls es in diesem Hinblick später Probleme gibt, kann man ja immer noch Testdaten generieren + nutzen, oder schemas bauen und so.
> 
> Dominik hat vorgeschlagen das in neuem PR zu machen, finde ich OK.

Geht von mir aus klar. Wenn sonst alles passt werde ich das mergen. Issue ist bereits erstellt und dem Sprint hinzugefügt. Habe mal dich (@ottojo ) assigned, weil du meinstest du bist schon dran.

2020-04-12 21:53 UTC, csacro approved these changes

2020-04-12 21:54 UTC, merged