Match config to json
SoPra-Team-17/LibCommon pull request #34
Opened 2020-04-09 19:40 UTC by authaldo

Fixes #30

2020-04-09 19:59 UTC, csacro commented
Füge bitte in Zukunft das PR zum Sprint-Plan hinzu. Das Issue kann dann gerne bei in Progess bleiben, denn das Issue selbst braucht ja keine Review ;-)

2020-04-09 20:04 UTC, csacro reviewed
Mir ist gerade aufgefallen, dass die "JSON keys" nicht mit dem matchconfig.schema aus dem Standard übereinstimmen. Wahrscheinlich passt das dann in der to_json auch nicht.

2020-04-09 20:19 UTC, authaldo commented
Ich habe mich an die Beispieldatei von Seite 11 des Standards gehalten, allerdings habe ich es nie wirklich mit dem Schema verglichen. Mit welchem Standard vergleichst du es? Dem aus dem Meilenstein Repo oder vom Standard Repo?

2020-04-09 20:21 UTC, csacro commented
Habe gar nicht in das Standard Dokument geschaut, sondern nur im gitlab repo das example aufgemacht

2020-04-09 20:39 UTC, authaldo commented
Du hast Recht, das Standarddokument aus dem Meilenstein-Repo nach welchem ich mich gerichtet habe ist mittlerweile wohl schon veraltet

2020-04-09 21:47 UTC, csacro approved these changes

2020-04-09 22:36 UTC, ottojo requested changes

2020-04-09 22:36 UTC, ottojo commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            * @note   A negative value corresponds to an infinite limit.
Kann man hier einen Datentyp für schaffen, der diesen Spezialfall abdeckt? Ich will kein extra prosa lesen müssen um den code zu verstehen, und der compiler kann das auch nicht. Vielleicht ein `std::optional` limit? Oder fancy `std::variant` oder halt eine kleine Helperklasse `Limit` oder so mit `bool Limit::isInfinite()`

Ich mag so "magische werte" nicht, das fängt bei "negativ = special" an, aber wenn ihr meint dass das overkill sei, sagt das mit :smile:

2020-04-09 22:36 UTC, ottojo commented on test/matchConfigTest.cpp
> +TEST(MatchConfigDecodingEncoding, MatchConfig) {
```suggestion
TEST(MatchConfig, MatchConfigDecodingEncoding) {
```
`TEST(TestSuiteName, TestName)`

[here](https://github.com/google/googletest/blob/master/googletest/docs/primer.md#simple-tests)

2020-04-09 22:36 UTC, ottojo commented on test/matchConfigTest.cpp
> +    std::string jsonString;
unused variable

2020-04-10 08:17 UTC, authaldo commented on src/datatypes/matchconfig/MatchConfig.hpp
> +            * @note   A negative value corresponds to an infinite limit.
Ich habe das ganze jetzt mal mit std::optional realisiert

2020-04-10 12:27 UTC, ottojo approved these changes

2020-04-10 12:27 UTC, merged