Gameplay data types
SoPra-Team-17/LibCommon pull request #39
Opened 2020-04-10 13:34 UTC by ottojo

fixes #26

2020-04-10 17:12 UTC, ottojo commented
`PropertyAction` blocked by #39

2020-04-10 22:17 UTC, ottojo commented
Ah ja da ist auch noch aus versehen die coverage gefixt... Danke, sonar!

2020-04-11 15:32 UTC, Marco5de commented
Sieht soweit ich das gesehen habe gut aus.

Wie können die überladenen Operatoren `==` und `!=` später verwendet werden?

2020-04-11 15:32 UTC, Marco5de approved these changes

2020-04-11 17:12 UTC, ottojo commented
> Wie können die überladenen Operatoren `==` und `!=` später verwendet werden?

Die habe ich für die Unit-Tests implementiert, dass man da `EXPECT_EQ(a, b)` schreiben kann [(hier)](https://github.com/SoPra-Team-17/LibCommon/pull/39/files#diff-9b1098854f2e63871e0f06e48dfe1b2aR27)

Im allgemeinen können die natürlich aber auch einfach so verwendet werden:
```c++
PropertyAction a{};
PropertyAction b{};
bool equality = a == b;
```

2020-04-11 18:51 UTC, authaldo requested changes
Ich würde stake (repräsentiert die Anzahl gesetzter Chips beim Roulette) als unsigned int implementieren, ansonsten passt aus meiner Sicht alles.

2020-04-11 18:51 UTC, authaldo commented on src/datatypes/gameplay/GambleAction.hpp
> +            int stake = 0;
Warum modellieren wir stake signed? Für mich wäre für die gesetzte Anzahl an Chips unsigned besser geeignet

```suggestion
            unsigned int stake = 0;
```

2020-04-11 18:51 UTC, authaldo commented on src/datatypes/gameplay/GambleAction.hpp
> +            [[nodiscard]] int getStake() const;
```suggestion
            [[nodiscard]] unsigned int getStake() const;
```

2020-04-11 18:51 UTC, authaldo commented on src/datatypes/gameplay/GambleAction.hpp
> +            GambleAction(bool successful, const util::Point &target, const util::UUID &characterId, int stake);
```suggestion
            GambleAction(bool successful, const util::Point &target, const util::UUID &characterId, unsigned int stake);
```

2020-04-11 18:51 UTC, authaldo commented on src/datatypes/gameplay/GambleAction.cpp
> +    GambleAction::GambleAction(bool successful, const util::Point &target, const util::UUID &characterId, int stake)
```suggestion
    GambleAction::GambleAction(bool successful, const util::Point &target, const util::UUID &characterId, unsigned int stake)
```

2020-04-11 18:51 UTC, authaldo commented on src/datatypes/gameplay/GambleAction.cpp
> +    int GambleAction::getStake() const {
```suggestion
    unsigned int GambleAction::getStake() const {
```

2020-04-11 18:58 UTC, authaldo approved these changes

2020-04-11 18:58 UTC, merged