initial scenario implementation
SoPra-Team-17/LibCommon pull request #41
Opened 2020-04-10 18:42 UTC by authaldo

Fixes #25

2020-04-12 01:53 UTC, ottojo commented on src/datatypes/scenario/FieldStateEnum.hpp
> +        { FieldStateEnum::BAR_TABLE, "BAR_TABLE" },
Hier mal wieder die Frage was hier bei parsing failure passieren soll. `BAR_TABLE` hört sich nicht nach sinnvollem default an, ich würde hier vielleicht einfach die Reihenfolge so ändern dass `FREE` oder so oben steht

2020-04-12 01:57 UTC, ottojo approved these changes

2020-04-12 07:34 UTC, authaldo commented
Ich würde erst den Netzwerk PR mergen

2020-04-12 20:50 UTC, ottojo approved these changes

2020-04-12 20:56 UTC, ottojo approved these changes

2020-04-12 22:12 UTC, csacro requested changes

2020-04-12 22:12 UTC, csacro commented on src/datatypes/scenario/FieldMap.hpp
> +            std::vector<std::vector<Field>> map;
getter für die komplette `map`, evtl. auch setter

2020-04-12 22:12 UTC, csacro commented on src/datatypes/scenario/Scenario.hpp
> +            std::vector<std::vector<FieldStateEnum>> scenario;
getter für komplettes `scenario`

2020-04-12 22:12 UTC, csacro commented on src/datatypes/scenario/Scenario.hpp
> +            [[nodiscard]] unsigned int getRowLength(unsigned int row) const;
Ist das sinnvoll, wenn im Standard steht, dass das Spielfeld nicht zwangsläufig rechteckig sein muss?

2020-04-13 00:39 UTC, ottojo commented
Wäre es aufwändig hier noch `spy::scenario::Scenario::operator==` zu definieren? Könnte ich für #43 gebrauchen.

2020-04-13 00:49 UTC, ottojo commented
Im std dokument ist in diesem Kapitel auch `State`, soll das hier auch noch mit rein?

2020-04-13 07:46 UTC, authaldo commented on src/datatypes/scenario/Scenario.hpp
> +            [[nodiscard]] unsigned int getRowLength(unsigned int row) const;
Die zwei Methoden sind ja genau dafür ausgelegt. Mit der Anzahl der Reihen und der jeweiligen Länge der Reihe decke ich ja genau den Fall ab.

2020-04-13 08:17 UTC, authaldo commented
Ich würde den State mit einem separaten PR abhandeln, da da vermutlich auch Änderungen außerhalb der Szenario Klassen notwendig werden.

2020-04-13 09:25 UTC, csacro commented on src/datatypes/scenario/Scenario.hpp
> +            [[nodiscard]] unsigned int getRowLength(unsigned int row) const;
Ok

2020-04-13 09:27 UTC, csacro commented
FYI: Der "Draft" von State ist aktuell unter datatypes/gameplay implementiert.

2020-04-13 09:54 UTC, authaldo commented
Ich finde man kann den State durchaus unter gameplay verortet lassen, ist ja deutlich mehr als nur das "Szenario"

2020-04-13 10:55 UTC, ottojo commented on src/datatypes/scenario/Scenario.cpp
> +    }
```suggestion
    bool Scenario::operator==(const Scenario &rhs) const {
        return scenario == rhs.scenario;
    }
```

2020-04-13 11:16 UTC, csacro approved these changes

2020-04-13 11:47 UTC, merged