Initial implementation of movement operation
SoPra-Team-17/LibCommon pull request #73
Opened 2020-04-24 20:21 UTC by authaldo

resolves #72

2020-04-26 12:25 UTC, authaldo commented
waiting for #75

2020-04-27 14:38 UTC, Marco5de commented on src/datatypes/gameplay/State.cpp
> +#include <iostream>
Altes Include?

2020-04-27 14:38 UTC, Marco5de commented on src/datatypes/gameplay/State.hpp
> +            character::CharacterSet characters{};
Warum jetzt public?

2020-04-27 14:39 UTC, csacro commented on src/datatypes/gameplay/State.hpp
> +            character::CharacterSet characters{};
Wieso ist das nicht mehr private?

2020-04-27 14:40 UTC, csacro commented on src/datatypes/gameplay/State.hpp
> +            character::CharacterSet characters{};
siehe marco

2020-04-27 14:42 UTC, authaldo commented on src/datatypes/gameplay/State.hpp
> +            character::CharacterSet characters{};
Der Getter lieferte const&, sodass man da für jeden Zugriff (wie das bewegen eines Charakters) den Setter hätte nutzen müssen. Habs jetzt mal mit einer Version des Getters die non const zurückliefert realisiert.

2020-04-27 14:48 UTC, csacro approved these changes

2020-04-27 15:27 UTC, ottojo requested changes

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.hpp
> +            static unsigned int getMoveDistance(const util::Point &p1, const util::Point &p2);
ich glaube diese Funktion wäre besser beim movement aufgehoben (spy::gameplay::Movement::getMoveDistance oder so)

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +        if (getMoveDistance(op.getFrom(), op.getTarget()) > 1) {        // only one step is allowed to avoid ambiguity
Gameplay-Frage: Kann man immer nur 1 schritt bewegen? Man kann ja mehrere Bewegungspunkte haben, aber die muss man halt nacheinander verwenden, oder?

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +        }
```suggestion
    bool State::isMovementValid(const gameplay::Movement &op) const {
        // only one step is allowed per game rules
        if (getMoveDistance(op.getFrom(), op.getTarget()) > 1) {
            return false;
        }
```

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +            return false;
```suggestion
        if (character == characters.end()) {
            // specified character UUID is not valid
            return false;
```

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +            return false;
```suggestion
        } else if (character->getCoordinates() != op.getFrom()) {
            // doesn't match characters position
            return false;
```

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +        auto charTarget = std::find_if(characters.begin(), characters.end(), [&op](const character::Character &c) {
```suggestion

        // search for character at target position
        auto charTarget = std::find_if(characters.begin(), characters.end(), [&op](const character::Character &c) {
```

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +        }
```suggestion
        if (charTarget != characters.end()) {
            // characters need to swap places
            charTarget->setCoordinates(op.getFrom());
        }
```

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +        }
```suggestion
        if (gadget.has_value()) {
            // pick up gadget
            character->addGadget(gadget.value());
            map.getField(op.getTarget()).removeGadget();
        }
```

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +        return std::max(abs(p1.x - p2.x), abs(p1.y - p2.y));
```suggestion
        return std::max(std::abs(p1.x - p2.x), std::abs(p1.y - p2.y));
```
wenn `std::max` dann auch `std::abs`

2020-04-27 15:27 UTC, ottojo commented on src/datatypes/scenario/Field.cpp
> +        Field::gadget = std::nullopt;
```suggestion
        Field::gadget.reset();
```

2020-04-27 15:27 UTC, ottojo commented on test/gameLogic/lineOfSightTests.cpp
> +static auto input = R"({ "scenario": [
why?

2020-04-27 15:38 UTC, authaldo commented on src/datatypes/gameplay/State.cpp
> +        if (getMoveDistance(op.getFrom(), op.getTarget()) > 1) {        // only one step is allowed to avoid ambiguity
Wie der Client das umsetzt würde ich ihm überlassen, aber aus Server Sicht ist man darauf angewiesen, dass pro Operation immer nur ein Schritt ausgeführt wird. Ansonsten ist das ganze nur durch Anfangs- und Endpunkt nicht mehr eindeutig.

2020-04-27 16:00 UTC, ottojo commented on src/datatypes/gameplay/Movement.cpp
> +    unsigned int Movement::getMoveDistance(const util::Point &p1, const util::Point &p2) {
würde das entweder static oder halt mit den membern machen

2020-04-27 16:00 UTC, ottojo commented on src/datatypes/gameplay/Movement.cpp
> +    unsigned int Movement::getMoveDistance(const util::Point &p1, const util::Point &p2) {
präferiert einfach die distanz von diesem movement

2020-04-27 16:02 UTC, ottojo commented on src/datatypes/gameplay/State.cpp
> +                                                                        // search for character at target position
ah ja also das sind langsam aber echt viele spaces... muss mir wohl ultrawide monitor kaufen...

2020-04-27 17:53 UTC, authaldo commented on src/datatypes/gameplay/Movement.cpp
> +    unsigned int Movement::getMoveDistance(const util::Point &p1, const util::Point &p2) {
Die Funktion ist bereits static (siehe .hpp)

2020-04-27 18:15 UTC, ottojo approved these changes

2020-04-27 18:34 UTC, merged